In [2]:

import numpy as np
import matplotlib.pyplot as plt

In [1]:
class PeriodicTrendDecomposion():
    def __init__(self, period_length, k1, k2, k3, n_inner=5, n_outer=2, robust=True, season_norm=True):
        '''
        '''
        self.period_length = period_length
        self.k1 = k1
        self.k2 = k2
        self.k3 = k3
        self.n_inner = n_inner
        self.n_outer = n_outer
        self.robust  = robust
        self.season_norm = season_norm
        return None
    # --------------------------------------------------------
    
    def transToSubseries(self, x):
        '''
        转换为周期子序列
        '''
        subseries = {}
        x_length = len(x)
        for i in range(x_length):
            subseries[i] = x[i::x_length]
        return subseries
    # --------------------------------------------------------
    
    def subseriesSmooth(self, subseries):
        '''
        subseries: dict, 由self.subseriesSmooth()函数得到的周期子序列
        '''
        C_t = []
        for a in subseries.values():
            C_t.append(self.LOESS(a, self.k2, expand=True))
        return C_t
    # --------------------------------------------------------
    
    def moveAverage(self, x, width):
        return [np.mean(x[i:i+width]) for i in range(len(x)-width)]
    # --------------------------------------------------------
    
    def seasonNormalization(self, x, period_length):
        '''
        将季节成分转换为严格周期函数
        '''
        n_period = len(x) // period_length
        P_t = [np.mean(x[i::period_length]) for i in range(n_period)]
        S_t = P_t * n_period
        return S_t, P_t
    # --------------------------------------------------------
    
    def kernelFuction(self, x, name='bisquare'):
        y = (1 - x*x)**2
        y[x>1] = 0
        return y
    # --------------------------------------------------------
    
    
    def LOESSSmooth(self, y, robust_weight, expand=False, robust=True):
        '''
        LOESS 平滑
        默认 x = [0, 1, ...]
        '''
        return None
    # --------------------------------------------------------
    
    def LOESSforSingle(self, x0, x, y, robust_weight, robust=True):
        
        return None
    # --------------------------------------------------------
    
    def __inner_loop(self, x):
        '''
        '''
        # Step 1:
        self.T_t_detrend = [a - self.T_t[i] for i, a in enumerate(x)]
        
        # Step 2:
        # 转换为周期子序列
        self.subseries = self.transToSubseries(self.T_t_detrend)
        # 
        self.C_t = self.subseriesSmooth(self.subseries)
        
        # Step 3:
        self.E_t = self.moveAverage(self.C_t, self.period_length)
        self.E_t = self.moveAverage(self.E_t, self.period_length)
        self.E_t = self.LOESS(self.E_t, self.k2)
        
        # Step 4: 计算季节成分
        self.S_t =  [self.C_t[i+self.period_length] - self.E_t[i] for i in range(self.series_length)]
        if self.season_norm:
            self.S_t, self.P_t = self.seasonNormalization(self.S_t, self.period_length)
        
        # Step 5: 去季节成分
        self.S_t_deseason = [a - self.S_t[i] for i, a in enumerate(x)]
        
        # Step 6:  计算趋势成分
        self.T_t = self.LOESS(self.S_t, self.k2)
        
        return None
    # --------------------------------------------------------
    
    def decompose(self, x):
        '''
        '''
        # 序列长度
        self.series_length = len(x)
        # 周期数量 不足一个周期的 则 舍去
        self.n_period = self.series_length // self.period_length
        
        # 趋势序列初始化
        self.T_t = [0.] * self.series_length
        
        for i_outer in range(self.n_outer):
            for i_inner in range(self.n_outer):
                self.__inner_loop(self, x)
            self.R_t = [a - self.T_t[i] - self.S_t[i] for i, a in enumerate(x)]
            if self.robust:
                self.robust_weight = self.kernelFuction(np.array(self.R_t)/(6*np.median(self.R_t)))
        return None
    # --------------------------------------------------------
        
    def outofsampelDecompose(self, x):
        '''
        '''
        # Step 1:
        # Step 2:
        # Step 3:
        # Step 4:
        
        
        return None
    # --------------------------------------------------------

TypeError: can't multiply sequence by non-int of type 'float'

In [3]:
print(not None)

True


In [21]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
x = np.arange(40).reshape(20,2)


y = poly.transform(x)
print(x)
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]]
[[ 1.  0.  1.]
 [ 1.  2.  3.]
 [ 1.  4.  5.]
 [ 1.  6.  7.]
 [ 1.  8.  9.]
 [ 1. 10. 11.]
 [ 1. 12. 13.]
 [ 1. 14. 15.]
 [ 1. 16. 17.]
 [ 1. 18. 19.]
 [ 1. 20. 21.]
 [ 1. 22. 23.]
 [ 1. 24. 25.]
 [ 1. 26. 27.]
 [ 1. 28. 29.]
 [ 1. 30. 31.]
 [ 1. 32. 33.]
 [ 1. 34. 35.]
 [ 1. 36. 37.]
 [ 1. 38. 39.]]
